services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/dev/quanta-volumes/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=quanta
